print('mulai')
print('ibu memberi perintah "beli 1 botol susu jika ada telur, beli 1 botol susu dan 6 biji telur"')
print('anak menjawab "ok"')
print('anak pergi ke toko')
print('anak sampai di toko')
print('apakah susu ada?')
print('ada')
print('anak mengecek harganya, cukup')
print('apakah ada telur?')
print('ada telur')
print('maka anak membeli 1 botol susu dan 6 telur')
print('anak membawa hasil belana kerumah')
print('anak sampe di rumah dan menyerahkan hasil belanja ke pada ibu')
print('The end')